name: Auto Cloudflare Scanner

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/init-python@v4
      with:
        python-version: '3.10'

    - name: Run IP Scanner
      run: python scanner.py

    - name: Commit and Push Results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add result.txt
        git commit -m "Update clean IPs" || exit 0
        git push
        
